# Uncomment the next line to define a global platform for your project
platform :ios, ’9.0’

target 'DistributionQuery' do

pod 'IQKeyboardManager'

  pod 'Masonry'
#  pod 'SVProgressHUD'
#  pod 'YYText'

  pod 'BmobSDK'
  
  pod 'JPush'

end
