# Uncomment the next line to define a global platform for your project
platform :ios, ’9.0’

target 'deko' do


pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'AFNetworking'

  pod 'MJRefresh'
  pod 'SDAutoLayout'
   pod 'FMDB/common' , '~>2.5'
     pod 'Masonry'

end
