# Uncomment the next line to define a global platform for your project
platform :ios, ’9.0’

target 'de444ko' do


pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'AFNetworking'

  pod 'MJRefresh'
  pod 'SDAutoLayout'
  
  
end
