source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'TechProject4' do
    
    pod 'JPush', '~> 3.0.9'
  pod 'YYText'
    pod 'BmobSDK'
#       pod 'SDWebImage', '~> 4.0.0-beta2'
#  pod 'PYSearch', '~> 0.3.5'
  pod 'MagicalRecord'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'KVOController'
  pod 'IQKeyboardManager'
  pod 'YYCategories'
  pod 'lottie-ios'
  pod 'AFNetworking'
  pod 'SDCycleScrollView','~> 1.3'

   pod 'FMDB/common' , '~>2.5'
  
  pod 'KVNProgress', '~> 2.3.1'
  pod 'Toast', '~> 3.1.0'
#     pod 'SVProgressHUD', '~> 2.0.4'
#     pod 'YYWebImage', '~> 1.0.5' #图片加载工具
#     pod 'MJExtension', '~> 3.0.13'

#   pod 'SVProgressHUD', '~> 2.0.4'
#  pod 'UITableView+FDTemplateLayoutCell'
#  pod 'FMDB/common' , '~>2.5'

      
      

end
